stages:
  generate_data:
    cmd: python src/generate_data.py
    deps:
      - src/generate_data.py
    outs:
      - data/dataset.csv
  
  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/dataset.csv
    outs:
      - models/model.joblib:
          cache: true
    metrics:
      - metrics.json:
          cache: false
