generate_data:
  n_samples: 1000
  n_features: 20
  n_informative: 15
  n_redundant: 5
  random_state: 42

train:
  model_type: "random_forest"
  n_estimators: 300  # Increased from 200
  max_depth: 10     # Increased from 5
  min_samples_split: 2
  random_state: 42
  test_size: 0.2
