name: feature-store-demo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas>=2.0.1  # Compatible with feast and great-expectations
  - numpy>=1.24.4
  - scikit-learn>=1.3.2
  - python-dotenv>=1.0.0
  - sqlite>=3.42.0  
  - jupyter>=1.0.0
  - ipykernel>=6.0.0
  - pip>=23.0.0
  - pip:
    - "dask[dataframe]>=2024.12.1"
    - great-expectations>=0.17.23
    - feast==0.42.0
    - dvc==3.30.3