version: '3'
services:
  superset:
    image: apache/superset
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=your_secret_key_here
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=admin@superset.com
      - ADMIN_PASSWORD=admin
      - PYTHONPATH=/app/pythonpath
    volumes:
      - ./superset_home:/app/superset_home
      - ../airflow/data:/data
      - ./superset_config.py:/app/pythonpath/superset_config.py
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: |
      bash -c 'if [ ! -f /app/superset_home/.init ]; then
        pip install pillow &&
        superset db upgrade &&
        superset fab create-admin --username $$ADMIN_USERNAME --firstname Superset --lastname Admin --email $$ADMIN_EMAIL --password $$ADMIN_PASSWORD &&
        superset init &&
        touch /app/superset_home/.init
      fi &&
      superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debugger'
